name: fsm
description: A library for finite state machine realization.
version: 0.0.1
homepage: https://github.com/ookami-kb/fsm

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dfunc: '>=0.3.0 <0.4.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
